# Containment evidence delivered to an independent auditor (spec.md strict tier
# req 6, and the Verification section). VPC Flow Logs are generated by the
# platform below the guest and written append-only to a store the auditor
# controls. The agent cannot alter or suppress them.

resource "aws_s3_bucket" "evidence" {
  bucket = "sealed-eval-evidence"

  tags = { Name = "sealed-eval-evidence" }
}

# Append-only: object versioning plus an Object Lock-style retention would be set
# on the auditor's own account. Versioning shown here; the bucket is owned by the
# auditor, not the lab.
resource "aws_s3_bucket_versioning" "evidence" {
  bucket = aws_s3_bucket.evidence.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_public_access_block" "evidence" {
  bucket = aws_s3_bucket.evidence.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Flow records for the whole subnet. traffic_type ALL captures accepted and
# rejected flows, so the auditor can confirm nothing left the seal.
resource "aws_flow_log" "seal" {
  vpc_id                   = aws_vpc.seal.id
  traffic_type             = "ALL"
  log_destination_type     = "s3"
  log_destination          = aws_s3_bucket.evidence.arn
  max_aggregation_interval = 60
}
